---
# easy Ubuntu nginx playbook as an example.
# this is a test for ec2 user-data  
# local.yml is used for pull-based Ansible setup.

- hosts: localhost 
  user: root 

  vars:
     #workers: use at template ansible_processor_count 
     connections : "1024"

     is_10_up: "'$ansible_distribution_version' >= '10.04'"
     is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"

  tasks:
     - include: nginx/tasks/nginx-task.yml

     - name: just check if local is updated.
       action: command echo "Hello Ansible."

  handlers:
     - name: restart nginx
       action: service name=nginx state=restarted
