---
# easy Ubuntu nginx playbook as an example.
- hosts: web-servers
  user: ubuntu 
  sudo: True

  vars:
     #workers: use at template ansible_processor_count 
     connections : "1024"

     is_10_up: "'$ansible_distribution_version' >= '10.04'"
     is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"

  tasks:
     - include: nginx/tasks/nginx-task.yml
  handlers:
     - name: restart nginx
       action: service name=nginx state=restarted
